name: test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v3

      - name: Install pnpm latest version
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm type-check
      - run: pnpm test
